trigger:
  - main
pr:
  - main

jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: yarn install --frozen-lockfile
      - script: docker run --name postgres --rm -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=ads-db -p 127.0.0.1:5432:5432 -d postgres
      - script: npx nx test hotel-management-system-backend --watch=false
      - script: npx nx run-many --target=build --all --parallel --maxParallel=4 --generatePackageJson
      - publish: $(System.DefaultWorkingDirectory)/dist/apps
        artifact: build