trigger:
  - main
pr:
  - main


variables:
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestId)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)

jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: yarn install --frozen-lockfile
        workingDirectory: hotel-management-system
      - script: npx nx format:check --base=origin/main
        workingDirectory: hotel-management-system
      - script: npx nx affected --base=origin/main -t lint --parallel=3
        workingDirectory: hotel-management-system/
      - script: npx nx affected --base=origin/main -t test --parallel=3 --configuration=ci
        workingDirectory: hotel-management-system/
      - script: npx nx affected --base=origin/main -t build --parallel=3
        workingDirectory: hotel-management-system/
